/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import java.awt.Toolkit;

/**
 *
 * @author Camil
 */
public class Fibra extends javax.swing.JFrame {

    double valor1,valor2,valor3,valor4,valor5,conectores,fusiones,perdidaC,perdidaTotal,ResultadoFinal;
    public Fibra() {
        initComponents();
        valor1=0;
        valor2=0;
        valor3=0;
        valor4=0;
        this.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/Icon.PNG")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Tx = new javax.swing.JRadioButton();
        Rx = new javax.swing.JRadioButton();
        Mensaje1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        WL1 = new javax.swing.JRadioButton();
        WL2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        longitud = new javax.swing.JTextField();
        Valor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Calcular = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        Mensaje2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Distancia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Resultado_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(25, 25, 25));

        Grupo1.add(Tx);
        Tx.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        Tx.setForeground(new java.awt.Color(233, 233, 233));
        Tx.setText("Tx");
        Tx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxMouseClicked(evt);
            }
        });

        Grupo1.add(Rx);
        Rx.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        Rx.setForeground(new java.awt.Color(233, 233, 233));
        Rx.setText("Rx");
        Rx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Rx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RxMouseClicked(evt);
            }
        });
        Rx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(Tx)
                .addGap(18, 18, 18)
                .addComponent(Rx)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tx)
                    .addComponent(Rx))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        Mensaje1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        Mensaje1.setForeground(new java.awt.Color(233, 233, 233));
        Mensaje1.setText("¿Qué valor desea saber?");
        getContentPane().add(Mensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(25, 25, 25));

        buttonGroup1.add(WL1);
        WL1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        WL1.setForeground(new java.awt.Color(233, 233, 233));
        WL1.setText("1310nm");
        WL1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonGroup1.add(WL2);
        WL2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        WL2.setForeground(new java.awt.Color(233, 233, 233));
        WL2.setText("1550nm");
        WL2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(WL1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(WL2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WL2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(WL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 210, 240, 50));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(233, 233, 233));
        jLabel2.setText("¿Qué longitud de onda desea manejar?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 360, -1));

        longitud.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        longitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longitudActionPerformed(evt);
            }
        });
        getContentPane().add(longitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 123, -1));

        Valor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorActionPerformed(evt);
            }
        });
        getContentPane().add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 114, -1));

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(233, 233, 233));
        jLabel3.setText("Digite la longitud de cada carrete");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        Calcular.setBackground(new java.awt.Color(233, 233, 233));
        Calcular.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        Calcular.setForeground(new java.awt.Color(65, 79, 91));
        Calcular.setText("Calcular");
        Calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });
        getContentPane().add(Calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        Volver.setBackground(new java.awt.Color(233, 233, 233));
        Volver.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        Volver.setForeground(new java.awt.Color(65, 79, 91));
        Volver.setText("Volver");
        Volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Mensaje2.setForeground(new java.awt.Color(233, 233, 233));
        Mensaje2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Mensaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 143, 235, 31));

        jPanel3.setBackground(new java.awt.Color(25, 25, 25));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 233, 233));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DISEÑO RED DE FIBRA OPTICA");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 6, 391, -1));

        Distancia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(Distancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 152, -1));

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(233, 233, 233));
        jLabel4.setText("Digite la distancia de la red");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        Resultado_label.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        Resultado_label.setForeground(new java.awt.Color(233, 233, 233));
        Resultado_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(Resultado_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 320, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxMouseClicked
        Mensaje2.setText("Digite el valor de Rx en dBm");
    }//GEN-LAST:event_TxMouseClicked

    private void RxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RxActionPerformed

    private void RxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RxMouseClicked
        Mensaje2.setText("Digite el valor de Tx en dBm");
    }//GEN-LAST:event_RxMouseClicked

    private void ValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorActionPerformed

    private void longitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longitudActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        if (Rx.isSelected()){
            try{
                valor1=Double.parseDouble(Valor.getText());
                if (WL1.isSelected()==true){
                    valor2=Double.parseDouble(longitud.getText()); //Longitud de cada carrete
                    valor3=Double.parseDouble(Distancia.getText()); //Distancia de la red
                    valor4=valor3/valor2; //El numero de carretes necesarios
                    valor5=valor4-1;//numero de fusiones
                    
                    perdidaC=valor3*0.38;
                    conectores=0.6*2;
                    fusiones=valor5*0.1;
                    System.out.println("Perdidas por cable: "+perdidaC+" Perdidas por conectores: "+conectores+" Perdidas por fusiones: "+fusiones);
                    perdidaTotal=perdidaC+conectores+fusiones;
                    ResultadoFinal=valor1-perdidaTotal;
                    Resultado_label.setText("Rx = "+ResultadoFinal+" dBm");
                }
                else{
                    if(WL2.isSelected()==true){
                        valor2=Double.parseDouble(longitud.getText()); //Longitud de cada carrete
                        valor3=Double.parseDouble(Distancia.getText()); //Distancia de la red
                        valor4=valor3/valor2; //El numero de carretes necesarios
                        valor5=valor4-1;//numero de fusiones
                    
                        perdidaC=valor3*0.22;
                        conectores=0.35*2;
                        fusiones=valor5*0.05;
                        System.out.println("Perdidas por cable: "+perdidaC+" Perdidas por conectores: "+conectores+" Perdidas por fusiones: "+fusiones);
                        perdidaTotal=perdidaC+conectores+fusiones;
                        ResultadoFinal=valor1-perdidaTotal;
                        Resultado_label.setText("Rx = "+ResultadoFinal+" dBm");
                    }
                }
            }
            catch(Exception E){
                Resultado_label.setText("Algo salio mal");
            }
        }
        else{
            if(Tx.isSelected()==true){
                try{
                    valor1=Double.parseDouble(Valor.getText());
                    if (WL1.isSelected()==true){
                        valor2=Double.parseDouble(longitud.getText()); //Longitud de cada carrete
                        valor3=Double.parseDouble(Distancia.getText()); //Distancia de la red
                        valor4=valor3/valor2; //El numero de carretes necesarios
                        valor5=valor4-1;//numero de fusiones

                        perdidaC=valor3*0.38;
                        conectores=0.6*2;
                        fusiones=valor5*0.1;
                        System.out.println("Perdidas por cable: "+perdidaC+" Perdidas por conectores: "+conectores+" Perdidas por fusiones: "+fusiones);
                        perdidaTotal=perdidaC+conectores+fusiones;
                        ResultadoFinal=valor1+perdidaTotal;
                        Resultado_label.setText("Tx = "+ResultadoFinal+" dBm");
                }
                    else{
                        if(WL2.isSelected()==true){
                        valor2=Double.parseDouble(longitud.getText()); //Longitud de cada carrete
                        valor3=Double.parseDouble(Distancia.getText()); //Distancia de la red
                        valor4=valor3/valor2; //El numero de carretes necesarios
                        valor5=valor4-1;//numero de fusiones
                    
                        perdidaC=valor3*0.22;
                        conectores=0.35*2;
                        fusiones=valor5*0.05;
                        System.out.println("Perdidas por cable: "+perdidaC+" Perdidas por conectores: "+conectores+" Perdidas por fusiones: "+fusiones);
                        perdidaTotal=perdidaC+conectores+fusiones;
                        ResultadoFinal=valor1+perdidaTotal;
                        Resultado_label.setText("Tx = "+ResultadoFinal+" dBm");
                    }
                    }
                }
                catch(Exception E){
                    Resultado_label.setText("Algo salio mal");
                }
            }
            else{
                Resultado_label.setText("Algo salio mal");
            }
        }
    }//GEN-LAST:event_CalcularActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        Design_net objeto = new Design_net();
        objeto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JTextField Distancia;
    private javax.swing.ButtonGroup Grupo1;
    private javax.swing.JLabel Mensaje1;
    private javax.swing.JLabel Mensaje2;
    private javax.swing.JLabel Resultado_label;
    private javax.swing.JRadioButton Rx;
    private javax.swing.JRadioButton Tx;
    private javax.swing.JTextField Valor;
    private javax.swing.JButton Volver;
    private javax.swing.JRadioButton WL1;
    private javax.swing.JRadioButton WL2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField longitud;
    // End of variables declaration//GEN-END:variables
}
