/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import java.awt.Toolkit;

/**
 *
 * @author Camil
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/Icon.PNG")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        salir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Boton5 = new javax.swing.JButton();
        Boton6 = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();
        Boton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Boton1 = new javax.swing.JButton();
        Boton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(560, 230));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(560, 209));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 136, -1, -1));

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 183, -1, -1));

        salir.setBackground(new java.awt.Color(233, 233, 233));
        salir.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        salir.setForeground(new java.awt.Color(65, 79, 91));
        salir.setText("Volver");
        salir.setBorderPainted(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jPanel3.setBackground(new java.awt.Color(25, 25, 25));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton5.setBackground(new java.awt.Color(233, 233, 233));
        Boton5.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        Boton5.setForeground(new java.awt.Color(65, 79, 91));
        Boton5.setText("Watts - dBm");
        Boton5.setBorderPainted(false);
        Boton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton5ActionPerformed(evt);
            }
        });
        jPanel3.add(Boton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        Boton6.setBackground(new java.awt.Color(233, 233, 233));
        Boton6.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        Boton6.setForeground(new java.awt.Color(65, 79, 91));
        Boton6.setText("Watts - dBw");
        Boton6.setBorderPainted(false);
        Boton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton6ActionPerformed(evt);
            }
        });
        jPanel3.add(Boton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        Boton2.setBackground(new java.awt.Color(233, 233, 233));
        Boton2.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        Boton2.setForeground(new java.awt.Color(65, 79, 91));
        Boton2.setText("Veces - dB");
        Boton2.setBorderPainted(false);
        Boton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2ActionPerformed(evt);
            }
        });
        jPanel3.add(Boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 134, -1));

        Boton4.setBackground(new java.awt.Color(233, 233, 233));
        Boton4.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        Boton4.setForeground(new java.awt.Color(65, 79, 91));
        Boton4.setText("dBw - Watts");
        Boton4.setBorderPainted(false);
        Boton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton4ActionPerformed(evt);
            }
        });
        jPanel3.add(Boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 134, -1));

        jLabel1.setBackground(new java.awt.Color(233, 233, 233));
        jLabel1.setFont(new java.awt.Font("Constantia", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 233, 233));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione el tipo de conversión que desea realizar");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 540, -1));

        Boton1.setBackground(new java.awt.Color(233, 233, 233));
        Boton1.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        Boton1.setForeground(new java.awt.Color(65, 79, 91));
        Boton1.setText("dB - Veces");
        Boton1.setBorderPainted(false);
        Boton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });
        jPanel3.add(Boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 134, -1));

        Boton3.setBackground(new java.awt.Color(233, 233, 233));
        Boton3.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        Boton3.setForeground(new java.awt.Color(65, 79, 91));
        Boton3.setText("dBm - Watts");
        Boton3.setBorderPainted(false);
        Boton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton3ActionPerformed(evt);
            }
        });
        jPanel3.add(Boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 134, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        dBVeces open= new  dBVeces();
        open.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Boton1ActionPerformed

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        VecesdB open= new  VecesdB();
        open.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Boton2ActionPerformed

    private void Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton3ActionPerformed
        dBmWatts open= new dBmWatts();
        open.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Boton3ActionPerformed

    private void Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton4ActionPerformed
        dBwWatts open = new dBwWatts();
        open.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Boton4ActionPerformed

    private void Boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton5ActionPerformed
        WattsdBm open = new WattsdBm();
        open.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Boton5ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.setVisible(false);
        Relacion open = new Relacion();
        open.setVisible(true);
    }//GEN-LAST:event_salirActionPerformed

    private void Boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton6ActionPerformed
        WattsdBw open = new WattsdBw();
        open.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Boton6ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton2;
    private javax.swing.JButton Boton3;
    private javax.swing.JButton Boton4;
    private javax.swing.JButton Boton5;
    private javax.swing.JButton Boton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
